---
- hosts: all
  roles:
    - { role: external_data_drive, when: external_data_drive__enabled }
    - { role: users, when: users__enabled }
    - { role: apt_basic, when: apt_basic__enabled }
    - { role: apt_localrepo, when: apt_localrepo__enabled }
    - { role: desktop, when: desktop__enabled }
    - { role: openedx, when: openedx__enabled }
    - { role: kalite, when: kalite__enabled }
    - { role: wikipedia, when: wikipedia__enabled }

 Always run this one last, since it will build the ISO
    - { role: build_iso, when: build_iso__enabled }

